In [2]:
import numpy as np
import pandas as pd
from typing import Tuple,List
from collections import Counter
import re
from typing import Union

In [3]:
##Ex 1
def checkDescending(list:np.array)->np.array:
    listDescending=list!=np.flip(np.sort(list))
    x=np.where(listDescending==False)
    newList=list[x[0][0]+1:x[0][1]+1]
    return newList
list=np.array([-4,3,5,3,2,1,-3,-4,-5,-4])
print(checkDescending(list))

[ 5  3  2  1 -3 -4]


In [8]:
##Ex2
def minMax(list:np.array)->np.array:
    aux=Counter(list)
    print(aux)
    listSorted=aux.most_common()
    print(listSorted)
    mostCommon=listSorted[0][0]
    lesscommon=listSorted[-1][0]
    return mostCommon,lesscommon
    
list=np.array([-4,3,5,3,2,1,-3,-4,-5,-4])
print(minMax(list))

Counter({-4: 3, 3: 2, 5: 1, 2: 1, 1: 1, -3: 1, -5: 1})
[(-4, 3), (3, 2), (5, 1), (2, 1), (1, 1), (-3, 1), (-5, 1)]
(-4, -5)


In [4]:
##Ex3
def minMaxMat(mat:np.array)->Tuple[int,int]:
    col=mat.max(axis=0)
    row=mat.min(axis=1)
    return col,row

mat = np.array([[1, 2, 3, 4],
                [1, -2, 3, -4],
                [3, 10, 3, 4]])
print(minMaxMat(mat))

(array([ 3, 10,  3,  4]), array([ 1, -4,  3]))


In [5]:
##Ex4
def prodMat(mat:np.array)->np.array:
    computeOnLine=int(input("Enter your choice:(must be 0/1): "))
    row=np.prod(mat,axis=computeOnLine)
    return row

mat = np.array([[1, 2, 3, 4],
                [1, -2, 3, -4],
                [3, 10, 3, 4]])
print(prodMat(mat))


Enter your choice:(must be 0/1): 


ValueError: invalid literal for int() with base 10: ''

In [6]:
##Ex5
def maxBetweenMat(matA:np.array,matB:np.array)->np.array:
    matBool=matA==matB
    x=np.where(matBool==False)
    if x[0].size>0:
        return x[0][0],x[1][0]
    return None


matA = np.array([[1, 2, 3, 4],
                [1, -2, 3, -4],
                [3, 10, 3, 4]])
matB = np.array([[1, 2, 3, 4],
                [1, -2, 3, -4],
                [3, 10, 3, 5]])

print(maxBetweenMat(matA,matB))

(2, 3)


In [44]:
##Ex 6
def intervalMat(mat:np.array,min:int,max:int)->Tuple[int,int]:
    matBool= mat[:]<max
    matBool2=mat[:]>min
    matList=matBool & matBool2
    x=np.where(matList==False)
    return x

matA = np.array([[1, 2, 3, 4],
                [1, -2, 3, -4],
                [3, 10, 3, 4]])
print(intervalMat(matA,0,5))

(array([1, 1, 2], dtype=int64), array([1, 3, 1], dtype=int64))


In [51]:
##Ex 7
'''

    The function takes one array as parameter and multiplies all elements smaller that 100 with 2, 
    until all elements are grater than 100. 
    The function returns the elements from vector that are grater that 150 and smaller than 200.
    Parameters

    arr : ndarray
       An array repesented by numpy.ndarray.
    Returns

    np.ndarray
        The elements from the modified array, that are grater than 150 and smaller than 200.
'''
def get_modified_array_elements(arr: np.ndarray) -> np.ndarray:
    while arr[arr < 100].any():
        arr[arr < 100] *= 2
    return arr[np.logical_and(arr > 150, arr < 200)]

a = np.array([230, 10, 284, 39, 76])
get_modified_array_elements(a)



array([160, 156, 152])

In [52]:
##Ex 8
    '''
    The function takes two arrays of the same size as parameters and returns another array containing the maximum values 
    of the two, on the corsponding positions.
    
    Parameters
    ----------
    a : ndarray
       An array repesented by numpy.ndarray.
    b : ndarray
       An array repesented by numpy.ndarray.
   
    Returns
    -------
    np.ndarray
        An array with the maximum values from the two vectors, on the coresponding positions.
    '''
def pair_max(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    return np.maximum(a, b)

a = np.array([3, 7, 9, 13, -10, 200, 3])
b = np.array([4, 5, -9, 100, 300, 230, 1])
pair_max(a, b)

array([  4,   7,   9, 100, 300, 230,   3])

In [55]:
##Ex8
'''
    The function takes a matrix as a parameter and returns the indices of the rows and columns of NaN values.  
    Parameters
    matrix : ndarray
        A two-dimensional matrix represented by numpy.ndarray.
    Return
    tuple
        A tuple with the indices of rows and the indices of columns.
'''
def get_row_col_indices(matrix: np.ndarray)->tuple:
    return np.where(np.isnan(matrix))

#input data
matrix =np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', delimiter = ',')
rand_rows = np.random.randint(0, 150, size = 10)
rand_cols = np.random.randint(0, 4, size = 10)
matrix[rand_rows, rand_cols] = np.nan
print(matrix)
get_row_col_indices(matrix)

[[5.1 3.5 1.4 0.2 nan]
 [4.9 3.  1.4 0.2 nan]
 [4.7 3.2 1.3 0.2 nan]
 [4.6 3.1 1.5 0.2 nan]
 [5.  3.6 1.4 0.2 nan]
 [5.4 3.9 1.7 0.4 nan]
 [4.6 3.4 1.4 0.3 nan]
 [5.  3.4 1.5 0.2 nan]
 [4.4 2.9 1.4 0.2 nan]
 [4.9 3.1 1.5 0.1 nan]
 [5.4 3.7 1.5 0.2 nan]
 [4.8 3.4 1.6 0.2 nan]
 [4.8 3.  1.4 0.1 nan]
 [4.3 3.  1.1 0.1 nan]
 [5.8 4.  1.2 0.2 nan]
 [nan 4.4 1.5 0.4 nan]
 [nan 3.9 1.3 0.4 nan]
 [5.1 3.5 1.4 0.3 nan]
 [5.7 3.8 1.7 0.3 nan]
 [5.1 3.8 1.5 0.3 nan]
 [5.4 3.4 1.7 0.2 nan]
 [5.1 3.7 1.5 0.4 nan]
 [4.6 3.6 1.  0.2 nan]
 [5.1 3.3 1.7 0.5 nan]
 [4.8 3.4 1.9 0.2 nan]
 [5.  3.  1.6 0.2 nan]
 [5.  3.4 1.6 0.4 nan]
 [5.2 3.5 1.5 0.2 nan]
 [5.2 3.4 1.4 0.2 nan]
 [4.7 3.2 1.6 0.2 nan]
 [4.8 3.1 1.6 0.2 nan]
 [5.4 3.4 1.5 0.4 nan]
 [5.2 4.1 1.5 0.1 nan]
 [5.5 4.2 1.4 0.2 nan]
 [4.9 3.1 1.5 0.1 nan]
 [5.  3.2 1.2 0.2 nan]
 [5.5 3.5 1.3 0.2 nan]
 [4.9 3.1 1.5 0.1 nan]
 [4.4 3.  1.3 0.2 nan]
 [5.1 3.4 1.5 0.2 nan]
 [5.  3.5 1.3 0.3 nan]
 [4.5 2.3 1.3 0.3 nan]
 [4.4 3.2 1.3 0.2 nan]
 [5.  3.5 1

(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  15,  16,  16,  17,  18,  19,  20,  21,  22,  23,
         24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,
         37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,
         50,  51,  52,  53,  54,  55,  55,  56,  57,  58,  59,  59,  60,
         61,  62,  63,  64,  64,  65,  66,  67,  68,  69,  70,  71,  72,
         73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,
         86,  87,  88,  89,  90,  91,  92,  92,  93,  94,  95,  96,  97,
         98,  99, 100, 101, 102, 103, 104, 104, 105, 106, 107, 108, 109,
        109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 120,
        121, 122, 123, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
        133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145,
        146, 147, 148, 149], dtype=int64),
 array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 4, 0, 4, 4, 4, 4,
       

In [116]:
#10
def get_elements_and_indices(arr: np.ndarray, k: int)-> Union[tuple, str] :
    '''
    The function takes an array and a value k as parameters.
    The function returns the greatest k elements from array and their indices.
    
    Parameters
    ----------
    arr : ndarray
       An array repesented by numpy.ndarray.
    k : int
       Minimum size for array and the number of elements returned.
   
    Returns
    -------
    np.ndarray
        An array containing the k gratest elements and their indices.
    '''
        
    if(len(arr) >= k):
        return arr[np.argpartition(arr, k)[:k]], np.argpartition(arr, k)[:k]
    else:
        return 'Size of array is too small!'
    
arr = np.array([1, 2, 11, 4, 5, 6, 7, 8, 9, 10])
print(arr)
get_elements_and_indices(arr, 5)

[ 1  2 11  4  5  6  7  8  9 10]


(array([4, 1, 2, 5, 6]), array([3, 0, 1, 4, 5], dtype=int64))